apiVersion: apps/v1
kind: Deployment
metadata:
  name: translation-system-api
spec:
  selector:
    matchLabels:
      app: translation-system-api
  template:
    metadata:
      labels:
        app: translation-system-api
    spec:
      containers:
        - name: translation-system-api
          image: ghcr.io/project-mtee/translation-system-service:1.1.4  # TODO
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /app/appsettings.json
              name: translation-systems
              subPath: appsettings.json
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 80
            initialDelaySeconds: 10
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "512Mi"
      volumes:
        - name: translation-systems
          configMap:
            name: translation-systems