apiVersion: apps/v1
kind: Deployment
metadata:
  name: translation-worker-multilingual-general
spec:
  selector:
    matchLabels:
      app: translation-worker-multilingual-general
  template:
    metadata:
      labels:
        app: translation-worker-multilingual-general
    spec:
      containers:
        - name: translation-worker-multilingual-general
          image: ghcr.io/project-mtee/translation-worker:1.1.1-modular-general  # TODO
          env:
            - name: MQ_HOST
              value: $(RABBITMQ_SERVICE_HOST)
            - name: MQ_PORT
              value: $(RABBITMQ_SERVICE_PORT)
            - name: MQ_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: rabbitmq
            - name: MQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: rabbitmq
            - name: MKL_NUM_THREADS
              value: "16"
          resources:
            requests:
              memory: "8G"
              cpu: "16.0"
            limits:
              memory: "8G"
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8000
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8000
            initialDelaySeconds: 30