apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: asr-upload
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 30m  # TODO
    nginx.ingress.kubernetes.io/limit-rpm: "2"  # TODO
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "1"  # TODO
spec:
  ingressClassName: nginx
  rules:
    - host: mt.cs.ut.ee  # TODO
      http:
        paths:
          - path: /api/speech-to-text
            pathType: Exact
            backend:
              service:
                name: clammit-asr
                port:
                  number: 80
  tls:
    - hosts:
        - mt.cs.ut.ee  # TODO
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: asr
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/limit-rpm: "10"  # TODO
spec:
  ingressClassName: nginx
  rules:
    - host: mt.cs.ut.ee  # TODO
      http:
        paths:
          - path: /api/speech-to-text/(.+)
            pathType: Prefix
            backend:
              service:
                name: asr
                port:
                  number: 80
  tls:
    - hosts:
        - mt.cs.ut.ee  # TODO