apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: mt.cs.ut.ee  # TODO
      http:
        paths:
          - path: /(translateproxy.*)
            pathType: Prefix
            backend:
              service:
                name: web-proxy
                port:
                  number: 80
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: website
                port:
                  number: 80
  tls:
    - hosts:
        - mt.cs.ut.ee  # TODO