apiVersion: v1
kind: Service
metadata:
  name: clammit-asr
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8438
  selector:
    app: clammit-asr
---
apiVersion: v1
kind: Service
metadata:
  name: clammit-file-translation
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8438
  selector:
    app: clammit-file-translation