apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  ports:
    - name: http
      protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    app: website
---
apiVersion: v1
kind: Service
metadata:
  name: web-proxy
spec:
  ports:
    - name: http
      protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    app: web-proxy